name: Heimdall CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install package (editable)
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest --maxfail=1 --disable-warnings -q
